crudexample/urls.py
from django.contrib import admin
from django.urls import path, include
from employee.views import emp
from signup.views import signaction
from login.views import loginaction


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('signup/',signaction),
    path('login/',loginaction),
]

employee/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.show),
    path('emp', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

employee/models.py
from django.db import models  
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee"

login/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.

employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"

employee/views.py
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee
# Create your views here.

def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees': employees})


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'index.html', {'form': form})



def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'edit.html', {'employee': employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})


def destroy(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

login/views.py
from django.shortcuts import render
import mysql.connector as sql
em=''
pwd=''
# Create your views here.
def loginaction(request):
    global em,pwd
    if request.method=="POST":
        m=sql.connect(host="localhost",user="root",passwd="PassWord",database='djangodb')
        cursor=m.cursor()
        d=request.POST
        for key,value in d.items():
            if key=="email":
                em=value
            if key=="password":
                pwd=value
        
        c="select * from users where email='{}' and password='{}'".format(em,pwd)
        cursor.execute(c)
        t=tuple(cursor.fetchall())
        if t==():
            return render(request,'error.html')
        else:
            return render(request,"welcome.html")

    return render(request,'login_page.html')

signup/views.py
from django.shortcuts import render
import mysql.connector as sql
fn=''
ln=''
s=''
em=''
pwd=''
# Create your views here.
def signaction(request):
    global fn,ln,s,em,pwd
    if request.method=="POST":
        m=sql.connect(host="localhost",user="root",passwd="PassWord",database='djangodb')
        cursor=m.cursor()
        d=request.POST
        for key,value in d.items():
            if key=="first_name":
                fn=value
            if key=="last_name":
                ln=value
            if key=="gender":
                s=value
            if key=="email":
                em=value
            if key=="password":
                pwd=value
        
        c="insert into users Values('{}','{}','{}','{}','{}')".format(fn,ln,s,em,pwd)
        cursor.execute(c)
        m.commit()

    return render(request,'signup_page.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/python_fevicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <title>Telusko</title>
</head>
<body>
<center>
    {% block content %}

    {% endblock %}
</center>
</body>
</html>

templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

templates/error.html
<html>
    <head>
        <title>Error page</title>
        <style>
            body{
                color: red;
                background-color: white;
                font-size: 30px;
            }
        </style>
    </head>
    <body>
        <center><h1>Invalid Entry(-_-)!</h1></center>
    </body>
</html>

templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

templates/login_page.html
<html>
    <head>
        <title>Signup Page</title>
        <style>
            body{
                font-family: Arial, Helvetica, sans-serif;
                background-color: white;
            }
            button{
                background-color: #4CAF50;
                width: 25%;
                padding: 15px;
                color: black;
                border: none;
                float: center;
                font-size: 15px;
            }
            label{
                font-size: 20px;
            }
            form{
                border: 3px solid #f1f1f1;
            }
            input[type=email],input[type=password]{
                width: 50%;
                font-size: 15px;
                margin: 8px 0px;
                padding: 12px 20px;
                display: inline-block;
                border: 2px solid green;
                box-sizing: border-box;
            }
            button:hover{
                opacity:0.7;

            }
            .container{
                padding: 50px;
                background-color: white;
            }
            .imgcontainer {
                text-align: center;
                margin: 24px 0 12px 0;
            }
              
            img.avatar {
                width: 20%;
                border-radius: 50%;
            }  
        </style>
    </head>
    <body>
        <center><h1>Login Form</h1></center>
        <form action="#" method="post">
            {% csrf_token %}
            {% load static %}
            <center><div class="container">
                <div class="imgcontainer">
                    <img src="{% static 'avatar_img1.jpg' %}" alt="Avatar" class="avatar">
                </div>
                <label for ='email'><b>UserEmail :  </b></label>
                <input type="email" placeholder="Enter email" name="email" float="right"  required><br>  
                <label for='password'><b>Password : </b></label>
                <input type="password" placeholder="Enter Password" name="password" required><br>  
                <button type="submit"><b>Login</b></button><br>     
                Don't have accounct <a href="http://localhost:8000/signup/"> register </a>
            </div></center>
        </form>
    </body>
</html>

templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
	<th>Employee ID</th> 
	<th>Employee Name</th>  
	<th>Employee Email</th>
	<th>Employee Contact</th>
	<th>Actions</th>
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}
{% csrf_token %}
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>  
</html>

templates/signup_page.html
<html>
    <head>
        <title>Signup Page</title>
        <style>
            body{
                font-family: Arial, Helvetica, sans-serif;
                background-color: white;
            }
            button{
                background-color: #4CAF50;
                width: 25%;
                padding: 15px;
                color: black;
                border: none;
                float: center;
                font-size: 15px;
            }
            label{
                font-size: 20px;
            }
            form{
                border: 3px solid #f1f1f1;
            }
            input[type=email],input[type=text]{
                width: 50%;
                font-size: 15px;
                margin: 8px 0px;
                padding: 12px 20px;
                display: inline-block;
                border: 2px solid green;
                box-sizing: border-box;
            }
            input[type=radio]{
                height: 18px;
                width: 18px;
            }
            button:hover{
                opacity:0.7;

            }
            .container{
                padding: 50px;
                background-color: white;
            }
            .imgcontainer {
                text-align: center;
                margin: 24px 0 12px 0;
            }
              
            img.avatar {
                width: 10%;
                border-radius: 50%;
            }  
        </style>
    </head>
    <body>
        <center><h1>Register From</h1></center>
        <form action="#" method="post">
            {% csrf_token %}
            {% load static %}
            <center><div class="container">
                <div class="imgcontainer">
                    <img src="{% static 'avatar_img2.png' %}" alt="Avatar" class="avatar">
                </div>
                <label for='first_name'><b>First Name : </b></label>
		        <input type='text' placeholder="Enter your first name" name='first_name' required><br>
		        <label for='last_name'><b>Last Name :</b></label>
		        <input type='text' placeholder='Enter your last name' name='last_name' required><br>
		        <label for='gender' ><b>Gender : </b></label>
		        <input type='radio' name='gender' value='male' required>
		        <label ><b>Male</b></label>
		        <input type='radio' name='gender' value='female' required>
		        <label ><b>Female</b></label><br>
            	<label for ='email'><b>Email Id :  </b></label>
            	<input type="email" placeholder="Enter email" name="email" float="right"  required><br>  
            	<label for='password'><b>Password : </b></label>
            	<input type="text" placeholder="Enter Password" name="password" required><br>  
            	<button type="submit"><b>Signup</b></button><br>     
            	Already an accounct <a href="http://localhost:8000/login/"> Login </a>
            </div></center>
        </form>
    </body>
</html>

templates/welcome.html
<html>
    <head>
        <title>Welcome Page</title>
        <style>
            body{
                background-color: black;
                color: blue;
                font-size: 30px;
            }
        </style>
    </head>
    <body>
        <center><h1>Welcome :-)</h1></center>
    </body>

</html